CREATE TABLE member (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(32),
	regist_ip varchar(16),
	created_on timestamp(6),
	updated_on timestamp(6),
	is_admin bool,
	profile varchar(32)
);



-- ----------------------------------------
-- Postgres | Table structure for member
-- ----------------------------------------
--DROP TABLE IF EXISTS "public"."member";
--CREATE TABLE "public"."member" (
--"id" serial4,
--"name" varchar(32) COLLATE "default",
--"regist_ip" varchar(16) COLLATE "default",
--"created_on" timestamp(6),
--"updated_on" timestamp(6),
--"is_admin" bool,
--"profile" jsonb
--);



insert into member (name, regist_ip, created_on, updated_on, is_admin, profile) VALUES 
('woo', '127.0.0.1', '2016-01-15 10:34:23', '2016-01-15 10:34:25.999', 't', '{"age":15}');

insert into member (name, regist_ip, created_on, updated_on, is_admin, profile) VALUES
('Five', '192.168.1.120', '2016-02-15 10:34:23', '2016-02-15 10:34:23.999', 'f', '{"age":15}');