CREATE TABLE member (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(32),
	regist_ip varchar(16),
	created_on timestamp(6),
	updated_on timestamp(6),
	is_admin bool
);

insert into member (name, regist_ip, created_on, updated_on, is_admin) VALUES 
('woo', '127.0.0.1', '2016-01-15 10:34:23', '2016-01-15 10:34:25', 't');

insert into member (name, regist_ip, created_on, updated_on, is_admin) VALUES
('Five', '192.168.1.120', '2016-01-15 10:34:23', '2016-01-15 10:34:25', 'f');